language: r

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    packages: libcairo2-dev libssl-dev libcurl4-openssl-dev libxml2-dev libgmp-dev

script: 
  - Rscript --vanilla build-dep-list.R graph gRbase gRain jsonlite plotly SHELF rjson svglite magrittr
  - make
